name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
    types:
      - opened
      - synchronized
  push:
    branches: [main, ci-config]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc:
          # This is kind of excessive, but gives us good information
          # about which versions we actually support. The list is
          # basically the oldest version of 7 that we can easily install,
          # and then the newest point release after each major update.
          - "7.10.3"
          - "8.0.2"
          - "8.2.2"
          - "8.4.4"
          - "8.6.5"
          - "8.8.4"
          - "8.10.4"
          - "latest" # currently 9.0.1
        # exclude all non-linux builds and then
        # add back just a recent GHC for each
        # of windows and macOS. That way we get
        # good version coverage on linux and a
        # smoke test on macOS/windows.
        include:
          - os: macOS-latest
            ghc: latest
          - os: windows-latest
            ghc: latest
    env:
      CONFIG: "--enable-tests --enable-benchmarks --test-show-details=direct"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1.4
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - run: cabal v2-update
    - run: cabal v2-freeze $CONFIG
    - uses: actions/cache@v2.1.3
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          $${ runner.os }}-${{ matrix.ghc }}-
    - run: cabal v2-build $CONFIG
    - run: cabal v2-test $CONFIG
    - run: cabal v2-haddock $CONFIG
    - run: cabal v2-sdist
