name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [main, ci-config]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.2"]
        ghc:
          # This is kind of excessive, but gives us good information
          # about which versions we actually support. The list is
          # basically the oldest version of 7 that we can easily install,
          # and then the newest point release after each major update.
          - "7.10.3"
          - "8.0.2"
          - "8.2.2"
          - "8.4.4"
          - "8.6.5"
          - "8.8.4"
          - "8.10.4"
          - "9.0.1"
          - latest
        # exclude all non-linux builds and then
        # add back just a recent GHC for each
        # of windows and macOS. That way we get
        # good version coverage on linux and a
        # smoke test on macOS/windows.
        include:
          - os: macOS-latest
            ghc: latest
          - os: windows-latest
            ghc: latest

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: actions/setup-haskell@v1.1.4
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Configure
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct

    - name: Freeze
      run: |
        cabal freeze

    - uses: actions/cache@v2.1.3
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Install dependencies
      run: |
        cabal build all --only-dependencies

    - name: Build
      run: |
        cabal build all

    - name: Test
      run: |
        cabal test all

# Stack builds are currently not working. Not sure why.
#  stack:
#    name: stack / ghc ${{ matrix.ghc }}
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        stack: ["2.3.1"]
#        ghc: ["8.8.4"]
#
#    steps:
#    - uses: actions/checkout@v2
#      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'
#
#    - uses: actions/setup-haskell@v1.1.4
#      name: Setup Haskell Stack
#      with:
#        ghc-version: ${{ matrix.ghc }}
#        stack-version: ${{ matrix.stack }}
#
#    - uses: actions/cache@v2.1.3
#      name: Cache ~/.stack
#      with:
#        path: ~/.stack
#        key: ${{ runner.os }}-${{ matrix.ghc }}-stack
#
#    - name: Install dependencies
#      run: |
#        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies
#
#    - name: Build
#      run: |
#        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
#
#    - name: Test
#      run: |
#        stack test --system-ghc
#
